/*
  Warnings:

  - The values [BILL_PAYMENT,TRANSFER,DEPOSIT] on the enum `TRANSACTION_TYPE` will be removed. If these variants are still used in the database, this will fail.

*/
-- CreateEnum
CREATE TYPE "TRANSACTION_CATEGORY" AS ENUM ('BILL_PAYMENT', 'TRANSFER', 'DEPOSIT');

-- AlterEnum
BEGIN;
CREATE TYPE "TRANSACTION_TYPE_new" AS ENUM ('DEBIT', 'CREDIT');
ALTER TABLE "transaction" ALTER COLUMN "type" TYPE "TRANSACTION_TYPE_new" USING ("type"::text::"TRANSACTION_TYPE_new");
ALTER TYPE "TRANSACTION_TYPE" RENAME TO "TRANSACTION_TYPE_old";
ALTER TYPE "TRANSACTION_TYPE_new" RENAME TO "TRANSACTION_TYPE";
DROP TYPE "TRANSACTION_TYPE_old";
COMMIT;

-- AlterTable
ALTER TABLE "transaction" ADD COLUMN     "category" "TRANSACTION_CATEGORY" NOT NULL DEFAULT 'TRANSFER';
